### ISSUE TITLE
Support persistent connection

### ISSUE THREAD

**Issue by iwai** [clue/php-redis-react#30]
@clue 
i'm tried add persistent connection, but do not know the correct implementation.
I want to code review, if you have time.
see: https://github.com/iwai/php-redis-react/commit/7866dbe28739ced26c190dc8080b2a9b0a805aacs

**Comment by clue** [comment]
> see: iwai@7866dbe

I suppose the correct link is https://github.com/iwai/php-redis-react/commit/7866dbe28739ced26c190dc8080b2a9b0a805aac ? :)

I'm not sure I understand the use-case, i.e. how this is going to be used and how this differs from the current behavior. Perhaps you can give some background?

**Comment by iwai** [comment]
thank you fast reply.
current working https://github.com/iwai/react-resque
my react-resque using persistent connection.
https://github.com/iwai/react-resque/blob/master/composer.json

More specific code is in this code.
https://github.com/iwai/react-resque/blob/master/src/Resque/RedisClient.php#L100

**Comment by clue** [comment]
Thanks for posting back @iwai.

I'm still not entirely sure what use case your code fulfills.

Apparently, your `PersistentConnection` class overwrites the `Stream` so that the underlying socket resource will not actually be closed when you invoke the `end()` method. Specifically, this code appears to be left out intentionally:

```php
    public function end()
    {
…
        $this->buffer->on('close', function () use ($that) {
            $that->close();
        });
    }
```

However, the underlying socket resource will never actually be reused afaict.

Can you give some insight into this?

**Comment by clue** [comment]
Closing this due to a lack of feedback.

Please comment if this is still an issue to you and we can reopen this :+1:
