### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by sm2017** [clue/php-redis-react#46]
How can I set a timeout for redis command , that means if I don't get response within a time then reject the promise

**Comment by clue** [comment]
I see you seem to have found https://github.com/reactphp/promise-timer already, but for completeness, here's how this can be used:

```php
$promise = $client->get('key');

$promise = React\Promise\Timer\timeout($promise, 1.0, $loop);

$promise->then($resolved, $rejected);
```

Note that this merely discards the results of the underlying operation and rejects with a `TimeoutException`. If does NOT "cancel" the underlying operation, so your Redis server will not notice this at all.

As a rule of thumb, Redis commands are really fast, so most people likely don't want to apply timeouts to individual commands anyway. Some of the commands that take longer also offer a timeout parameter, so that this is handled entirely server-side, such as `BLPOP`.

I hope this helps :+1:
