### ISSUE TITLE
Switch to use React / Socket, instead of Socket Client

### ISSUE THREAD

**Issue by aedart** [clue/php-redis-react#50]
Hi Clue

Due to the major changes in react (which you have contributed to), I am sadly no longer able to use the package. The main reason is that this package depends on the `React / SocketClient` package.

Can you please update the package's dependencies and release it as version 2.x (important so that you don't break compatibility for those that use version 1.x)

**Comment by clue** [comment]
Thanks for reporting and I agree :+1: 

I'll have to postpone this for a couple of weeks but will get back to this asap. PRs would also be much appreciated :+1:

**Comment by aedart** [comment]
Ty for the quick replay... I'll give the update a go, then a make a pull request.

**Comment by aedart** [comment]
Hi again - can you please create another branch for version 2.x - Having some issues with you dependencies / mocks, which I'm not the most qualified to resolve.

If you create a new branch, I'll make a pull request for it, then you can review the changes.

**Comment by clue** [comment]
I'd rather like to look forward here. May I ask you to just file your PR against the `master` branch? We can still look into providing a BC-branch for older versions at a later point :+1:

**Comment by clue** [comment]
Small status update: I've just released an intermediary v1.1.0 release which updates the SocketClient version to the latest version :shipit: 

I'll release another intermediary v1.2.0 shortly which also accepts a `React\Socket\ConnectorInterface` instead of the legacy `React\SocketClient\ConnectorInterface` without causing a BC break. While this doesn't fix this issue completely, this should relax this situation significantly.

The major bump to newest components has to be postponed to the v2.0.0 release because we currently expose the legacy `React\SocketClient\ConnectorInterface` on our API, which means we have a direct dependency on the deprecated react/socket-client, which does only support react/stream < v0.7.

**Comment by clue** [comment]
Small status update: I've just released an intermediary v1.2.0 release which now supports a `React\Socket\ConnectorInterface`, so this should relax this situation significantly :shipit: 

The major bump to newest component is coming soon-ish :+1:
